home:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

boutique:
    path: /{_locale}/boutique
    controller: App\Controller\BoutiqueController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

rayon:
    path: /{_locale}/rayon/{idCategory}
    controller: App\Controller\BoutiqueController::rayon
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

search:
    path: /{_locale}/recherche
    controller: App\Controller\BoutiqueController::search
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier:
    path: /{_locale}/panier/
    controller: App\Controller\PanierController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier.ajouter:
    path: /{_locale}/panier/add/{productId}
    controller: App\Controller\PanierController::panierAjouter
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier.enlever:
    path: /{_locale}/panier/remove/one/{productId}
    controller: App\Controller\PanierController::panierEnlever
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier.supprimer:
    path: /{_locale}/panier/remove/all/{productId}
    controller: App\Controller\PanierController::panierSupprimer
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

panier.vider:
    path: /{_locale}/panier/remove/all
    controller: App\Controller\PanierController::panierVider
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

user.accueil:
    path: /{_locale}/user/
    controller: App\Controller\UserController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

user.inscription:
    path: /{_locale}/user/new
    controller: App\Controller\UserController::new
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'