index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

contact:
    path: /{_locale}/contact
    controller: App\Controller\DefaultController::contact
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: 'fr'

boutique:
    path: /boutique
    controller: App\Controller\BoutiqueController::index

rayon:
    path: /rayon/{idCategory}
    controller: App\Controller\BoutiqueController::rayon

search:
    path: /recherche/{searchText}
    controller: App\Controller\BoutiqueController::search
    defaults:
        searchText: ""